### ISSUE TITLE
Drop old rubies support?

### ISSUE THREAD

**Issue by deivid-rodriguez** [CocoaPods/Molinillo#127]
I wanted to start using `require_relative` for internal requires, for speedier code loading, but it's not available on 1.8.7. Thoughts on dropping support for old rubies that have reached their end of life?

**Comment by segiddins** [comment]
I’m ok with dropping 1.8.7 and 1.9.3 for the next minor release, but I want to keep supporting 2.0 for CocoaPods. Let’s give this a few days to make sure no other consumers of Molinillo have any concerns

**Comment by greysteil** [comment]
Big 👍 from me.

**Comment by segiddins** [comment]
Done in https://github.com/CocoaPods/Molinillo/pull/129
