### ISSUE TITLE
Is Molinillo exhaustive?

### ISSUE THREAD

**Issue by joliss** [CocoaPods/Molinillo#64]
Hey @segiddins,

I'm reading [ARCHITECTURE.md](https://github.com/CocoaPods/Molinillo/blob/master/ARCHITECTURE.md) and the source, and I'm still trying to answer the following question: Is Molinillo guaranteed to find a solution if one exists?

In other words, if we construct a pathological case where a solution exists but is hard to find, will Molinillo

* take a very long time and eventually find the solution (exhaustive), or
* report that no solution exists (non-exhaustive)?

Please let me know and I'll try and send a pull request to update the documentation.

**Comment by segiddins** [comment]
The goal is that it will, but there are always bugs

**Comment by joliss** [comment]
Thanks!
