### ISSUE TITLE
Ruby 2.3.3:Cant reslove the circular dependency between os and os

### ISSUE THREAD

**Issue by manjunathsoftwares** [CocoaPods/Molinillo#87]
Hi All,

I am using ruby version 2.3.3

I am trying to run Cucumber Q2.
One of my gem expecting os ~>0.9
Bundler could not find compatible versions for gem "os":
  In Gemfile:
  XXXXXXXXXXXXX was resolved to 1.0.7, which depends on
      os (~> 0.9) x86-mingw32

Could not find gem 'os (~> 0.9) x86-mingw32', which is required by gem 'xxxxx

when i try to install that gem file its giving below error

D:\>gem install os -v 0.9
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between os and os

Can someone help here?

below is my gem list
D:\>gem list

*** LOCAL GEMS ***

addressable (2.5.1)
bigdecimal (1.2.8)
builder (3.2.3)
bundler (1.15.1)
capybara (2.14.4)
childprocess (0.7.1)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
did_you_mean (1.0.0)
diff-lcs (1.3)
ffi (1.9.18 x86-mingw32
gherkin (4.1.3)
httpclient (2.8.3)
io-console (0.4.5)
json (1.8.3)
mime-types (3.1)
mime-types-data (3.2016
mini_portile2 (2.2.0)
minitest (5.8.5)
multi_json (1.12.1)
multi_test (0.1.2)
net-telnet (0.1.1)
nokogiri (1.8.0 x86-min
os (1.0.0)
parallel (1.12.0)
parallel_tests (2.15.0,
power_assert (0.2.6)
psych (2.1.0)
public_suffix (3.0.0, 2
rack (2.0.3)
rack-test (0.7.0)
rake (10.4.2)
rdoc (4.2.1)
require_relative (1.0.3
rspec (3.6.0, 2.14.0)
rspec-core (3.6.0, 2.14
rspec-expectations (3.6
rspec-mocks (3.6.0, 2.1
rspec-support (3.6.0)
rubyzip (1.2.1)
selenium-webdriver (2.5
test-unit (3.1.5)
websocket (1.2.4)
xpath (2.1.0)

**Comment by segiddins** [comment]
That is correct: https://rubygems.org/gems/os/versions/0.9.0 depends on itself.

**Comment by manjunathsoftwares** [comment]
What does below error mean
ERROR: While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
There is a circular dependency between os and os

**Comment by greysteil** [comment]
Hi @manjunathsoftwares. It means the gem maintainer made a slipup and accidentally created a circular dependency. In this case, that circularity comes from the gem explicitly depending on itself (see the link @segiddins shared).

The good news is that we handle circular dependencies a little better in Bundler 1.16.0. If you run `gem install bundler --pre` it will update you to a pre-release of that, which should allow you to bundle install just fine.
