### ISSUE TITLE
Two different sources providing the same pod yields wrong resolved version

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/Molinillo#88]
We have two pod repos that include the same pod, one with sources and one with binary form (for development speed up or other internal reasons).

It seems that when we upgrade to Molinillo version 0.6.x it resolves an incorrect version.

SourcesFormRepo:
``` 
PodA with published versions [1.0.0, 1.0.1, 1.0.2]
```
BinaryFormRepo
```
PodA with published versions [1.0.2] 
```

Given the Podfile:
```ruby
source 'source-repo.git'
source 'binary-repo.git'

pod 'PodA', '~> 1.0'

target 'SomeApp'
```

This will resolve back to version PodA of 1.0.1 instead of 1.0.2 despite the fact that both sources and binary repo both have version 1.0.2 published.

With Molinillo 0.5.x it correctly returns PodA 1.0.2 from the sources repo since the sources repo is defined first in the Podfile.

We are working on trying to get a sample project in the meantime for you but it's a little bit harder because it requires the same pod published in two different repos.

/cc @greysteil @segiddins

**Comment by segiddins** [comment]
Can you reproduce in a Molinillo integration spec? It's possible the bug is in CocoaPods integration

**Comment by dnkoutso** [comment]
yeap working on it to identify 100% if it's in molinillo versus CocoaPods itself. Will update or close this issue once we get a better idea on which part is causing it.

**Comment by justinseanmartin** [comment]
We made a simple repro case for it, simulating the same dependency structure that triggers the bug internally. That looks something like this for a DAG:

Data/Tests -> Data
Data/Tests -> Testing
Data -> Core
Testing -> Core

https://github.com/justinseanmartin/cannonpodder

To repro, checkout that repo and run `bundle exec pod install`. We'd expect that Core version `1.0.0` should be chosen.

We published all 3 pods to 2 different spec repos:
https://github.com/justinseanmartin/test-specs/
https://github.com/justinseanmartin/test-specs2/

`test-specs` contains both `1.0.0` and `1.0.1`
`test-specs2` contains only `1.0.1`

With molinillo 0.5.7, it picks `1.0.1` of Core
With molinillo 0.6.x (tried all 4 versions), it picks `1.0.0` of Core

It is still unclear if this is caused by cocoapods integration (https://github.com/CocoaPods/CocoaPods/pull/6900) of molinillo or this library itself. The version of Core that is selected varies based on the ordering of the spec repo `sources` within the Podfile.

**Comment by segiddins** [comment]
@justinseanmartin what version of Molinillo? 0.6.3 ? My _best_ guess is it has to do with the ordering CocoaPods is returning in `search_for`, but I'm not certain

**Comment by dnkoutso** [comment]
@segiddins I believe we tried all versions of 0.6.x as we were trying to narrow this down.

**Comment by segiddins** [comment]
Does something like the following patch fix it?

```diff
diff --git a/lib/cocoapods/resolver/lazy_specification.rb b/lib/cocoapods/resolver/lazy_specification.rb
index a9a24dfc..13b210de 100644
--- a/lib/cocoapods/resolver/lazy_specification.rb
+++ b/lib/cocoapods/resolver/lazy_specification.rb
@@ -58,7 +58,7 @@ module Pod
 
           versions_by_source.flat_map do |source, versions|
             versions.map { |version| LazySpecification.new(name, version, source) }
-          end
+          end.sort_by(&:version)
         end
       end
     end
```

**Comment by dnkoutso** [comment]
Will try it out and report back.

**Comment by dnkoutso** [comment]
@segiddins with this change I get:

```
Installing Core (1.0.0)
Installing Data (1.0.0)
Installing Testing (1.0.0)
```
So it actually picks 1.0.0 for all pods versus without it I get what the original report says:

```
Installing Core (1.0.0) 
Installing Data (1.0.1)
Installing Testing (1.0.1)
```

**Comment by segiddins** [comment]
Basically, right now CocoaPods isn't returning specs sorted by version, which it should be doing. My patch ensures that searching for a dependency will always return specs in order by version, rather than by source.

**Comment by greysteil** [comment]
The sort fix makes sense to me. Will leave this one to you guys.

**Comment by dnkoutso** [comment]
Great. If we know now the results are now sorted by version anymore then this is the right fix. Will make a PR later today and close this one.

Thank you!

**Comment by dnkoutso** [comment]
With this patch the trivial case is fixed, however, in a more complicated scenario despite specifying `--sources` (and therefore the order) during invocation we are receiving some Pods that should from binary repo coming from source repo instead.

We will do a side-by-side comparison of the old and new to identify the point where this occurs.

**Comment by dnkoutso** [comment]
@greysteil, @segiddins we compared side-by-side:

CocoaPods 1.3.1 with Molinillo 0.5.x
CocoaPods 1.3.1 with Molinillo 0.6.x + the integration with CocoaPods [PR](https://github.com/CocoaPods/CocoaPods/pull/6900) without any other changes.

The two implementations differ in `resolution.rb` method `attempt_to_activate` where the list of possibilities for 0.5.x includes only a single possibility of the pod requested from the correct source versus in 0.6.x the list of possibilities includes two (as many as source repos) possibilities and potentially the first one is chosen because the requirement is satisfied.

Starting to think there are two issues here one about the version sorting and one about filtering out possibilities due to their source or at least prioritize possibilities based on the order of sources the user has provided. Maybe those two issues are related or the same but I have not confirmed yet.

**Comment by segiddins** [comment]
> Starting to think there are two issues here one about the version sorting and one about filtering out possibilities due to their source or at least prioritize possibilities based on the order of sources the user has provided. Maybe those two issues are related or the same but I have not confirmed yet.

Both of those sound to me like things that need to be done in CocoaPods -- Molinillo has no notion of "sources"

**Comment by dnkoutso** [comment]
👍 thanks for this clarification it helps narrow down further.
