### ISSUE TITLE
[Master] Use unexpect source when have multi-sources

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/Molinillo#97]
I have many spec repos and some pods are same version in multi-sources. I known it is a very dangerous, but I could not to do anything . : (
The Podfile:
```
source 'git@myhost.com:iOS/publicthird_binary_repo.git'
source 'git@myhost.com:iOS/product_binary_repo.git'
```
There is a pod named `GYDataCenter(1.1.1-binary)` in the two spec repos.

Now, I use CocoaPods v1.3.1, the CP will use the first source which clone from `publicthird_binary_repo`.

But, I use master branch (CocoaPods and molinillo), the `GYDataCenter` will be used from `product_binary_repo`.

I try to put some logs:
```
: 323: Creating possibility state for GYDataCenter (1 remaining)
: 324: Attempting to activate [GYDataCenter (0.1.1.1-binary)(/Users/whirlwind/.cocoapods/repos/product_binary_repo/GYDataCenter/0.1.1.1-binary/GYDataCenter.podspec.json), GYDataCenter (0.1.1.1-binary)(/Users/whirlwind/.cocoapods/repos/publicthird_binary_repo/GYDataCenter/0.1.1.1-binary/GYDataCenter.podspec.json)]
: 324: Found existing spec ([GYDataCenter (0.1.1.1-binary)(/Users/whirlwind/.cocoapods/repos/product_binary_repo/GYDataCenter/0.1.1.1-binary/GYDataCenter.podspec.json), GYDataCenter (0.1.1.1-binary)(/Users/whirlwind/.cocoapods/repos/publicthird_binary_repo/GYDataCenter/0.1.1.1-binary/GYDataCenter.podspec.json)])
......
-> Using GYDataCenter (0.1.1.1-binary)(/Users/whirlwind/.cocoapods/repos/product_binary_repo/GYDataCenter/0.1.1.1-binary/GYDataCenter.podspec.json)
```

I'm not sure whose bug is, and I open this issue in this.

**Comment by segiddins** [comment]
Molinillo has no notion of sources, all that logic lives in CocoaPods

**Comment by segiddins** [comment]
CocoaPods would be the correct place for CocoaPods issues
